### ISSUE TITLE
4번 솔루션

### ISSUE THREAD

**Issue by moran991231** [all1m-algorithm-study/LeetCode-Solutions#29]
[https://leetcode.com/problems/median-of-two-sorted-arrays/](url)
올라와 있는 2개의 솔루션이 어딘가 이상합니다.
한 솔루션은 input과 output이 문제와 다르고, 한 솔루션은 문제에서 제시한 시간복잡도를 만족하지 않는 것 같습니다.
확인바랍니다

**Comment by kim-jhyeon** [comment]
이슈를 발행해주셔서 정말 감사드립니다!

말씀하신 문제를 운영진에서 인지하였으며, 제출된 코드들 중 릿코드에서 Accept되지 않는 풀이가 있는지 운영진에서 다시 검토하고 있습니다.

추후 진행 상황에 대해 공지해드리겠습니다.

**Comment by moran991231** [comment]
넵 수고 많으십니다!

**Comment by iknoom** [comment]
제출된 코드들을 검토한 결과 아래 솔루션들이 Accept를 받지 못하거나 문제에서 제시한 조건을 만족하지 못함을 확인했습니다.

**Accept를 받지 못하는 솔루션**
 - 4-gusrb3164.cpp : Error
 - 45-fivestar1103.c : Time limit Exceeded

**문제에서 제시하는 조건을 만족하지 못하는 솔루션**
- 4.cpp(sally0226님) : 시간복잡도를 만족하지 못함
- 41-fivestar1103.py : 공간복잡도를 만족하지 못함
- 43.py(Spoof-UoS님) : 조건을 만족하지 못함(You must not convert the inputs to integer directly)
- 347-gusrb3164.cpp : 시간복잡도를 만족하지 못함(Your algorithm's time complexity must be better than O(n log n))
- 443-yongjoonseo.py, 443-yongjoonseo.md : 공간복잡도를 만족하지 못함
